// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveConfigMetum struct {
	Namespace string             `json:"namespace"`
	Checksum  string             `json:"checksum"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Field struct {
	Namespace   string             `json:"namespace"`
	FieldID     string             `json:"fieldId"`
	Type        *string            `json:"type"`
	Description *string            `json:"description"`
	CreatedBy   string             `json:"createdBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type Function struct {
	Namespace   string             `json:"namespace"`
	FunctionID  string             `json:"functionId"`
	Version     int32              `json:"version"`
	Status      *string            `json:"status"`
	Type        *string            `json:"type"`
	Args        []string           `json:"args"`
	Values      []string           `json:"values"`
	ReturnType  *string            `json:"returnType"`
	CreatedBy   string             `json:"createdBy"`
	PublishedBy *string            `json:"publishedBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}

type Namespace struct {
	ID          string             `json:"id"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedBy   string             `json:"createdBy"`
}

type Rule struct {
	Namespace   string             `json:"namespace"`
	RuleID      string             `json:"ruleId"`
	Version     int32              `json:"version"`
	Status      *string            `json:"status"`
	Logic       *string            `json:"logic"`
	Conditions  []byte             `json:"conditions"`
	CreatedBy   string             `json:"createdBy"`
	PublishedBy *string            `json:"publishedBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}

type Terminal struct {
	Namespace  string             `json:"namespace"`
	TerminalID string             `json:"terminalId"`
	CreatedBy  string             `json:"createdBy"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Workflow struct {
	Namespace   string             `json:"namespace"`
	WorkflowID  string             `json:"workflowId"`
	Version     int32              `json:"version"`
	Status      *string            `json:"status"`
	StartAt     string             `json:"startAt"`
	Steps       []byte             `json:"steps"`
	CreatedBy   string             `json:"createdBy"`
	PublishedBy *string            `json:"publishedBy"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	PublishedAt pgtype.Timestamptz `json:"publishedAt"`
}
