// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountFieldsByNamespace(ctx context.Context, namespace string) (int64, error)
	CountTerminalsByNamespace(ctx context.Context, namespace string) (int64, error)
	CreateField(ctx context.Context, arg CreateFieldParams) error
	CreateFunction(ctx context.Context, arg CreateFunctionParams) error
	CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error
	CreateRule(ctx context.Context, arg CreateRuleParams) error
	CreateTerminal(ctx context.Context, arg CreateTerminalParams) error
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	DeactivateFunction(ctx context.Context, arg DeactivateFunctionParams) error
	DeactivateRule(ctx context.Context, arg DeactivateRuleParams) error
	DeactivateWorkflow(ctx context.Context, arg DeactivateWorkflowParams) error
	DeleteActiveConfigChecksum(ctx context.Context, namespace string) error
	DeleteField(ctx context.Context, arg DeleteFieldParams) error
	DeleteFunction(ctx context.Context, arg DeleteFunctionParams) error
	DeleteNamespace(ctx context.Context, id string) error
	DeleteRule(ctx context.Context, arg DeleteRuleParams) error
	DeleteTerminal(ctx context.Context, arg DeleteTerminalParams) error
	DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error
	FieldExists(ctx context.Context, arg FieldExistsParams) (bool, error)
	FunctionExists(ctx context.Context, arg FunctionExistsParams) (bool, error)
	GetActiveConfigChecksum(ctx context.Context, namespace string) (*ActiveConfigMetum, error)
	GetActiveFunctionVersion(ctx context.Context, arg GetActiveFunctionVersionParams) (*GetActiveFunctionVersionRow, error)
	GetActiveRuleVersion(ctx context.Context, arg GetActiveRuleVersionParams) (*Rule, error)
	GetActiveWorkflowVersion(ctx context.Context, arg GetActiveWorkflowVersionParams) (*Workflow, error)
	GetDraftFunctionVersion(ctx context.Context, arg GetDraftFunctionVersionParams) (*GetDraftFunctionVersionRow, error)
	GetDraftRuleVersion(ctx context.Context, arg GetDraftRuleVersionParams) (*Rule, error)
	GetDraftWorkflowVersion(ctx context.Context, arg GetDraftWorkflowVersionParams) (*Workflow, error)
	GetField(ctx context.Context, arg GetFieldParams) (*GetFieldRow, error)
	GetFunction(ctx context.Context, arg GetFunctionParams) (*GetFunctionRow, error)
	GetMaxFunctionVersion(ctx context.Context, arg GetMaxFunctionVersionParams) (interface{}, error)
	GetMaxRuleVersion(ctx context.Context, arg GetMaxRuleVersionParams) (interface{}, error)
	GetMaxWorkflowVersion(ctx context.Context, arg GetMaxWorkflowVersionParams) (interface{}, error)
	GetNamespace(ctx context.Context, id string) (*Namespace, error)
	GetRule(ctx context.Context, arg GetRuleParams) (*Rule, error)
	GetTerminal(ctx context.Context, arg GetTerminalParams) (*GetTerminalRow, error)
	GetWorkflow(ctx context.Context, arg GetWorkflowParams) (*Workflow, error)
	ListActiveFunctions(ctx context.Context, namespace string) ([]*ListActiveFunctionsRow, error)
	ListActiveRules(ctx context.Context, namespace string) ([]*Rule, error)
	ListActiveWorkflows(ctx context.Context, namespace string) ([]*Workflow, error)
	ListAllActiveConfigChecksums(ctx context.Context) ([]*ActiveConfigMetum, error)
	ListFields(ctx context.Context, namespace string) ([]*ListFieldsRow, error)
	ListFunctionVersions(ctx context.Context, arg ListFunctionVersionsParams) ([]*ListFunctionVersionsRow, error)
	ListFunctions(ctx context.Context, namespace string) ([]*ListFunctionsRow, error)
	ListNamespaces(ctx context.Context) ([]*Namespace, error)
	ListRuleVersions(ctx context.Context, arg ListRuleVersionsParams) ([]*Rule, error)
	ListRules(ctx context.Context, namespace string) ([]*Rule, error)
	ListTerminals(ctx context.Context, namespace string) ([]*ListTerminalsRow, error)
	ListWorkflowVersions(ctx context.Context, arg ListWorkflowVersionsParams) ([]*Workflow, error)
	ListWorkflows(ctx context.Context, namespace string) ([]*Workflow, error)
	PublishFunction(ctx context.Context, arg PublishFunctionParams) error
	PublishRule(ctx context.Context, arg PublishRuleParams) error
	PublishWorkflow(ctx context.Context, arg PublishWorkflowParams) error
	RefreshNamespaceChecksum(ctx context.Context, ns string) error
	RuleExists(ctx context.Context, arg RuleExistsParams) (bool, error)
	TerminalExists(ctx context.Context, arg TerminalExistsParams) (bool, error)
	UpdateField(ctx context.Context, arg UpdateFieldParams) error
	UpdateFunction(ctx context.Context, arg UpdateFunctionParams) error
	UpdateRule(ctx context.Context, arg UpdateRuleParams) error
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) error
	UpsertActiveConfigChecksum(ctx context.Context, arg UpsertActiveConfigChecksumParams) error
	WorkflowExists(ctx context.Context, arg WorkflowExistsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
